name: Release Docker image
on:
  push:
  workflow_dispatch:
jobs:
  build_and_push:
    name: Build and push container to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Generate image tags
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=branch
          type=sha
          0.3

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
